"""empty message

Revision ID: 91cfe59c44de
Revises: 
Create Date: 2024-01-12 12:16:12.791673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cfe59c44de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negative_bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bill_information_link', sa.String(), nullable=True),
    sa.Column('case_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('expanded_category', sa.String(), nullable=True),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('legiscan_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negative_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negative_bills_checksum'), ['checksum'], unique=True)

    op.create_table('reps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('modified', sa.String(), nullable=False),
    sa.Column('political_party', sa.String(), nullable=True),
    sa.Column('reelection_date', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('capitol_address', sa.String(), nullable=True),
    sa.Column('capitol_phone', sa.String(), nullable=True),
    sa.Column('district_address', sa.String(), nullable=True),
    sa.Column('district_phone', sa.String(), nullable=True),
    sa.Column('ftm_eid', sa.Integer(), nullable=True),
    sa.Column('legiscan_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reps_checksum'), ['checksum'], unique=True)

    op.create_table('reps_to_negative_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rep_id', sa.String(), nullable=False),
    sa.Column('negative_bills_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reps_to_negative_bills')
    with op.batch_alter_table('reps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reps_checksum'))

    op.drop_table('reps')
    with op.batch_alter_table('negative_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negative_bills_checksum'))

    op.drop_table('negative_bills')
    # ### end Alembic commands ###
