name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=./ pytest --junitxml=test-results.xml

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml

  comment:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Comment PR
        uses: actions/github-script@v3.1
        with:
          script: |
            const fs = require('fs');
            const data = fs.readFileSync('test-results.xml', 'utf8');
            const results = data.match(/tests="(\d+)" failures="(\d+)" errors="(\d+)"/)
            const comment = `:test_tube: **Test Report**
                              - Tests: ${results[1]}
                              - Failures: ${results[2]}
                              - Errors: ${results[3]}`
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
            })